### ISSUE TITLE
compile on Mint 19.3 fails

### ISSUE THREAD

**Issue by pdarcos** [congard/nvidia-system-monitor-qt#6]
Following the instructions to compile from scratch I get an error when I run make:

Scanning dependencies of target qnvsm
[ 33%] Building CXX object CMakeFiles/qnvsm.dir/qnvsm_autogen/mocs_compilation.cpp.o
[ 33%] Building CXX object CMakeFiles/qnvsm.dir/src/mainwindow.cpp.o
[ 44%] Building CXX object CMakeFiles/qnvsm.dir/src/main.cpp.o
[ 55%] Building CXX object CMakeFiles/qnvsm.dir/src/processes.cpp.o
[ 66%] Building CXX object CMakeFiles/qnvsm.dir/src/utilization.cpp.o
[ 77%] Building CXX object CMakeFiles/qnvsm.dir/src/utils.cpp.o
[ 88%] Building CXX object CMakeFiles/qnvsm.dir/src/worker.cpp.o
/home/Documents/nvidia/nvidia-system-monitor-qt/src/utilization.cpp: In function ‘void drawGrid(QWidget*, QPainter*)’:
/home/Documents/nvidia/nvidia-system-monitor-qt/src/utilization.cpp:32:13: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     x0 = fm.horizontalAdvance(text);
             ^~~~~~~~~~~~~~~~~
/home/Documents/nvidia/nvidia-system-monitor-qt/src/utilization.cpp:36:13: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     x0 = fm.horizontalAdvance(text);
             ^~~~~~~~~~~~~~~~~
/home/Documents/nvidia/nvidia-system-monitor-qt/src/utilization.cpp: In function ‘void drawStatusObjects(std::vector<QRect, std::allocator<QRect> >&, UtilizationData*, QPainter*)’:
/home/Documents/nvidia/nvidia-system-monitor-qt/src/utilization.cpp:73:24: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     int textWidth = fm.horizontalAdvance("100%"); // because max width will be only at 100%
                        ^~~~~~~~~~~~~~~~~
CMakeFiles/qnvsm.dir/build.make:114: recipe for target 'CMakeFiles/qnvsm.dir/src/utilization.cpp.o' failed
make[2]: *** [CMakeFiles/qnvsm.dir/src/utilization.cpp.o] Error 1
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/qnvsm.dir/all' failed
make[1]: *** [CMakeFiles/qnvsm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I installed sudo apt install qtdeclarative5-dev but it seems QT doesn't like the horizontalAdvance member...

Any clues?

Thanks

**Comment by congard** [comment]
Hi, check this: https://github.com/congard/nvidia-system-monitor-qt/issues/1#issuecomment-538628068

**Comment by pdarcos** [comment]
Yeah I saw that and it's working fine now.
Had to update my Qt to latest version.
Thanks!
